version: '3'

services:
  redis:
    image: 'bitnami/redis:5.0'
    container_name: 'redis'
    environment:
      - REDIS_PASSWORD=123456
    ports:
      - '16379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local
